#!/bin/bash

######################################
### Makes playlist and then plays it
######################################

vidplayer=${VIDPLAYER:-mpv}
rannum=$RANDOM
plfile="/tmp/playlist.$rannum.m3u"

for i in $*; do
    reali=$(realpath "$i")
    searchpath=$(realpath "$reali")

    echo "$searchpath"

    if [ "$scriptdebug" ]; then
        find "$searchpath" -type f \
            | grep -i -E '.(wmv|mp4|mkv|avi|flv|webm)$' \
            | tee "$plfile"
    else
        find "$searchpath" -type f \
            | grep -i -E '.(wmv|mp4|mkv|avi|flv|webm)$' \
            >> "$plfile"
    fi

    echo "Playlist saved in $plfile"
done

"$vidplayer" "$playerargs" "$plfile"
