#!/usr/bin/env python
''' '''

import os
import sys
import random

abs = os.path.abspath
pics = os.listdir(os.path.expanduser('~/Pictures/Wallpapers'))
for pic in pics:
    abs(pic)


random_index = random.randrange(0, len(pics))
print('[ %s ]' % random_index + ' === ' + pics[random_index])
wallpic = os.path.expanduser("~/Pictures/Wallpapers/%s" % pics[random_index])
print(wallpic)
command = 'feh --bg-fill %s' % wallpic
print(command)
os.system(command)

