#!/bin/bash

player=${player:-mpv}
playlist="/tmp/tmsulist.${RANDOM}.m3u"
tags=$*

if [ -n "$tags" ]; then
    for tag in $tags;do
        if [ "$scriptdebug" ]; then
            tmsu files "$tag" \
                | tee "$playlist"
        else
            tmsu files "$tag" \
                >> "$playlist"
        fi
    done

    "$player" "$playlist"
elif [ -z "$tags" ]; then
    echo "please enter one of these tags: "
    tmsu tags
fi
