#!/bin/bash

player=${player:-mpv}
playlist="/tmp/tmsulist.${RANDOM}.m3u"
tags=$*

for tag in $tags;do
    tmsu files "$tag" \
        >> "$playlist"
done

echo "created $playlist!"
echo "$playlist" | xclip
